#!/usr/bin/env bash
# Transfers a file from local source to remote source.
# u:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    file_path=$1
    server_ip=$2
    username=$3
    ssh_key_path=$4

    scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $username@$server_ip:~

fi



$scp_command
