#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Define the redirection configuration
redirection_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Add other server configurations as needed
}
"

# Replace the default Nginx configuration with the redirection configuration
sed -i '/server {/a\'"$redirection_config" "$nginx_conf"

# Restart Nginx to apply the changes
service nginx restart