#!/usr/bin/env bash
#Installs NGINX to open port 80

#sudo apt-get -y update
#sudo apt-get -y install nginx
#service nginx start

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
