#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd.

#But only:
#username
#user id
#Home directory path for the user

while read -r passwd
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
