#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd.

#But only:
#username
#user id
#Home directory path for the user

LIST="$(cat /etc/passwd)"
for i in $LIST
do
	echo "$i" | cut -d ':' -f1,3,6
done